name: 'Tevel NPM Authentication'
description: 'Perform Tevel private registry npm authentication'
inputs:
    npm_auth:
      description: npm authentication token
      required: true
    npm_auth_prefix:
      description: npm authentication prefix
      required: true
    npm_email:
      description: npm user email
      required: true
    npm_registry:
      description: npm private registry address
      required: true
runs:

  using: "composite"
  steps: 
    - run: |
        echo "${{ inputs.npm_auth_prefix }}:_authToken="${{ inputs.npm_auth }}"
        email=${{ inputs.npm_email }}
        always-auth=true
        registry=${{ inputs.npm_registry }}" > ~/.npmrc
      shell: sh
